spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: hoangson145juzk@gmail.com
    password: aqbq onja jbkd nmiu

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: "jdbc:mysql://localhost:3306/model_trade"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: ModelTradeAPI
server:
  port: 8080
  servlet:
    context-path: /model_trade


jwt:
  signerKey: "Ns44SXXKgd2+MeKoAGqvg0xiRA+nFfpDY4b5wshQp1iwmVp2f1FzLjvC0JD6hE/e"

vnpay:
  vnp_TmnCode: P9UWP1CB
  vnp_HashSecret: HURMICNNGBF0CIFLWK66NGB46JLWVSG3
  vnp_Url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return_Url: http://localhost:8080/model_trade/api/exchange/vnp-return


