spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/model_trade"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: ModelTradeAPI
server:
  port: 8080
  servlet:
    context-path: /model_trade


